version: "3"
services:

  blobber:
    build:
      context: ${DOCKER_CODEBASE}
      dockerfile: ./docker.aws/build.blobber/Dockerfile

    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${AGENT_CONTAINER}

    environment:
    - DOCKER=true

    user: ${ZCHAIN_USER}:${ZCHAIN_GROUP}

    command: /0chain/bin/blobber --deployment_mode 0 --keys_file /0chain/config/blobber.txt --nodes_file nodes --files_dir /0chain/files --badger_dir /0chain/data

    ports:
    - ${AGENT_PORT}:${AGENT_PORT}

    volumes:
    - /0chain/${AGENT_DIR}/config:/0chain/config
    - /0chain/${AGENT_DIR}/log:/0chain/log
    - /0chain/${AGENT_DIR}/data:/0chain/data
    - /0chain/${AGENT_DIR}/data/badgerdb:/0chain/data/badgerdb
    - /0chain/${AGENT_DIR}/data/badgerdb/blobberstate:/0chain/data/badgerdb/blobberstate
    - /0chain/${AGENT_DIR}/files:/0chain/files

    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 10M

    networks:
      default:

    restart: ${RESTART_POLICY}

networks:
  default:
    driver: bridge

